### ISSUE TITLE
interactive issue in network chart

### ISSUE THREAD

**Issue by ericccc123** [AnyChart/AnyChart#168] opened 2021-02-12 06:30 UTC
There is no interactive edges could be shown between two nodes when I use the network.
For example: the relationship between two nodes is  bidirectional( {from: 1, to: 2}  also {from:2, to: 1}), however the edge can only show from 1 to 2 but it could show from 2 to 1.

**Comment by Shestac92** [comment] 2021-02-13 13:07
@ericccc123 
The current version of the Network graph was designed that way. It doesn't support cycled connections between nodes. We will take it into account for future updates.

**Comment by sturdystablestalwart** [comment] 2023-11-24 16:32
@ericccc123 

You've created a duplicate of an [issue](https://github.com/AnyChart/AnyChart/issues/145) that is already being worked on.
Regardless, thank you for your report, and if you have any additional questions or concerns, I'm here to help!

**Closed by sturdystablestalwart** 2023-11-24 16:32 UTC
